### PR TITLE
Draft support

### PR DESCRIPTION
**Pull request by johannhof**
This adds support for drafts (see README changes).

### CODE REVIEW

**Comment by johannhof** [comment]
@LucioFranco @tak1n want to take a look? :)

**Comment by LucioFranco** [comment]
LGTM but I just read through it without a test.

**Comment by johannhof** [comment]
Whoops Travis was failing because I forgot a cargo fmt

**Comment by LucioFranco** [comment]
@johannhof the tests seem to fail on linux.
```bash
failures:

---- custom_paths stdout ----
	<!DOCTYPE html>
<html>
    <head>
        <title>test</title>
    </head>
    <body>
        <h1>index.html</h1>

        
This is my Index page!


 <a href="2015/hello/index.html">Date variables</a>

 <a href="2015/05/5/03/3/06/05/20/index.html">All date variables</a>

 <a href="test/thing2.html">Custom paths with leading slash</a>

 href="test/hello/index.html">Variables</a>

 <a href="test/thing.html">Custom paths</a>

 <a href="test/thing4/index.html">Boom without trailing slash</a>

 <a href="test/thing3/index.html">Boom</a>

 <a href="test/hello/world.abc">Variables file name</a>

 <a href="posts/no-path.html">Custom paths</a>

 <a href="test/thing.html">Custom paths</a>

 <a href="test/thing3/index.html">Boom</a>

 <a href="test/thing2.html">Custom paths with leading slash</a>

 <a href="test/thing4/index.html">Boom without trailing slash</a>


    </body>
</html>

 href="test/hello/index.html">Variables</a>

 <a href="test/hello/world.abc">Variables file name</a>


    </body>
</html>

 
thread 'custom_paths' panicked at 'assertion failed: edit distance between "<!DOCTYPE html>\n<html>\n    <head>\n        <title>test</title>\n    </head>\n    <body>\n        <h1>index.html</h1>\n\n        \nThis is my Index page!\n\n\n <a href=\"2015/hello/index.html\">Date variables</a>\n\n <a href=\"2015/05/5/03/3/06/05/20/index.html\">All date variables</a>\n\n <a href=\"test/thing2.html\">Custom paths with leading slash</a>\n\n <a href=\"test/thing.html\">Custom paths</a>\n\n <a href=\"test/thing4/index.html\">Boom without trailing slash</a>\n\n <a href=\"test/thing3/index.html\">Boom</a>\n\n <a href=\"posts/no-path.html\">Custom paths</a>\n\n <a href=\"test/hello/index.html\">Variables</a>\n\n <a href=\"test/hello/world.abc\">Variables file name</a>\n\n\n    </body>\n</html>\n\n" and "<!DOCTYPE html>\n<html>\n    <head>\n        <title>test</title>\n    </head>\n    <body>\n        <h1>index.html</h1>\n\n        \nThis is my Index page!\n\n\n <a href=\"2015/hello/index.html\">Date variables</a>\n\n <a href=\"2015/05/5/03/3/06/05/20/index.html\">All date variables</a>\n\n <a href=\"test/hello/index.html\">Variables</a>\n\n <a href=\"test/hello/world.abc\">Variables file name</a>\n\n <a href=\"posts/no-path.html\">Custom paths</a>\n\n <a href=\"test/thing.html\">Custom paths</a>\n\n <a href=\"test/thing3/index.html\">Boom</a>\n\n <a href=\"test/thing2.html\">Custom paths with leading slash</a>\n\n <a href=\"test/thing4/index.html\">Boom without trailing slash</a>\n\n\n    </body>\n</html>\n\n" is 30 and not 0, see diffset above', /home/lucio.franco/.cargo/registry/src/github.com-1ecc6299db9ec823/difference-0.4.1/src/lib.rs:86
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    custom_paths

test result: FAILED. 16 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```
but this commit seems to pass on [travis](https://travis-ci.org/cobalt-org/cobalt.rs/jobs/148778184).

**Comment by johannhof** [comment]
Hmm it seems these aren't read in alphabetical order for you for some reason. Maybe we should not trust in that and add an alphabetic sort ourselves in case a post doesn't have a date. But I wouldn't say it's an issue with this PR :)

**Pull request closed without merging**
