### PR TITLE
Rename some refactored fct

### PR DESCRIPTION
**Pull request by Geobert**
Here is the follow up of https://github.com/cobalt-org/cobalt.rs/pull/369 applying your comments!

### CODE REVIEW

**Comment by Geobert** [comment]
I'll wait for https://github.com/cobalt-org/cobalt.rs/pull/370 to merged, otherwise I have issues with tests

**Comment by Geobert** [comment]
@epage : Changing `generate_posts` code to call the factorised version `generate_doc` makes excerpt generation fail.
Doesn't make any sense as I've compare the code, and it's the same. Can it be the cloning?

**Comment by Geobert** [comment]
yeah, the cloning was not a good idea, this is done while rendering excerpt: https://github.com/cobalt-org/cobalt.rs/blob/master/src/document.rs#L312
hence the error.

**Comment by epage** [comment]
Looks good.  let me know when its squashed.

**Pull request merged**
