### PR TITLE
extensive usage of Result in main

### PR DESCRIPTION
**Pull request by benaryorg**
I pretty much just stuck *error-chain* into `main()`. The tests still pass (I guess you didn't really write a lot of tests for this) and the actual error handling is more central.

I still feel like someone should go over the code and add some [`chain_err`s](https://brson.github.io/error-chain/error_chain/index.html#chaining-errors) all over the place but that's up to you.

I also did not really test the current output, it probably doesn't show a lot of useful information as long as there is no `chain_err`.

I also added a mechanism to declare dependencies (e.g. serve needs build) which then even further centralises error handling.

Please do me a favour and let someone thoroughly review those changes.

### CODE REVIEW

**Comment by benaryorg** [comment]
Oh yeah, I forgot: I linked to https://github.com/brson/error-chain/issues/65 in e6cf321; should there be a new release of error-chain; please throw out that git stuff immediately and replace it by an actual version.

**Comment by benaryorg** [comment]
Sorry. Forgot `cargo fmt`. **Now** the tests pass.

**Comment by benaryorg** [comment]
New version of *error-chain* renders the [above comment](https://github.com/cobalt-org/cobalt.rs/pull/162#issuecomment-261755778) obsolete.

**Comment by epage** [comment]
Closed by #291

**Pull request closed without merging**
