### PR TITLE
update liquid version (fixes issue #16)

### PR DESCRIPTION
**Pull request by Liamsi**
updated liquid version and other deps (builds with rust 1.0, now)
and added a quick explanation on howto run (for rust newbies like me and people who do not read through the code first)

### CODE REVIEW

**Comment by tak1n** [comment]
Thanks for this PR but I removed the Cargo.lock file from the git repo.
Also cobalt.rs does use many unstable features so it's not 1.0.0 compat, I'll update the installation instructions with the proper rust version.

**Comment by Liamsi** [comment]
Thank you for the fast reply! 
One question though: What exactly does it mean its not compatible to 1.0.0? It just compiled fine here. But I only tried the basic example. It also worked fine.
I am just curious. I am very new to Rust and still learning a lot.

**Comment by tak1n** [comment]
Can you list the exact rust version you are using?

For the rust 1.0.0 stable release cobalt will not work because it's using many unstable features, e.g.: https://doc.rust-lang.org/std/fs/trait.PathExt.html

To use these features you have to use a nightly release as far as I know.
I'm new to rust too, so could be misinformed here
For the rust 1.0.0 stable release cobalt will not work because it's using many unstable features, e.g.: https://doc.rust-lang.org/std/fs/trait.PathExt.html

To use these features you have to use a nightly release as far as I know.
I'm new to rust too, so could be misinformed here

**Comment by Liamsi** [comment]
```
rustc -V
rustc 1.0.0-dev (built 2015-05-17)
```

**Comment by tak1n** [comment]
Okay the -dev suffix seems weird, how did you install rust?

Here the differences between stable, beta and nightly:

Rust Stable
```
cobalt.rs ➤ rustc --version                                                                                                                                                                             git:master
rustc 1.0.0 (a59de37e9 2015-05-13) (built 2015-05-14)
cobalt.rs ➤ cargo build                                                                                                                                                                                 git:master
   Compiling regex-syntax v0.1.0
   Compiling regex v0.1.32
   Compiling liquid v0.1.1 (https://github.com/cobalt-org/liquid-rust#96df4716)
   Compiling cobalt v0.0.1 (file:///home/benny/Development/rust/cobalt-org/cobalt.rs)
src/cobalt.rs:94:5: 94:36 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/cobalt.rs:94     file.read_to_string(&mut text);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/document.rs:78:13: 78:21 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
src/document.rs:78         let mut html = match self.as_html(post_data) {
                               ^~~~~~~~
src/lib.rs:1:1: 1:22 error: unstable feature
src/lib.rs:1 #![feature(path_ext)]
             ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
src/lib.rs:2:1: 2:21 error: unstable feature
src/lib.rs:2 #![feature(fs_walk)]
             ^~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
src/lib.rs:3:1: 3:18 error: unstable feature
src/lib.rs:3 #![feature(core)]
             ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
src/lib.rs:4:1: 4:32 error: unstable feature
src/lib.rs:4 #![feature(path_relative_from)]
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the stable release channel
error: aborting due to 4 previous errors
Could not compile `cobalt`.

To learn more, run the command again with --verbose.
```

Rust Beta
```
cobalt.rs ➤ rustc --version                                                                                                                                                                             git:master
rustc 1.1.0-beta (cd7d89af9 2015-05-16) (built 2015-05-16)
cobalt.rs ➤ cargo build                                                                                                                                                                                 git:master
   Compiling cobalt v0.0.1 (file:///home/benny/Development/rust/cobalt-org/cobalt.rs)
src/cobalt.rs:94:5: 94:36 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/cobalt.rs:94     file.read_to_string(&mut text);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/document.rs:78:13: 78:21 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
src/document.rs:78         let mut html = match self.as_html(post_data) {
                               ^~~~~~~~
src/lib.rs:1:1: 1:22 error: unstable feature
src/lib.rs:1 #![feature(path_ext)]
             ^~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib.rs:2:1: 2:21 error: unstable feature
src/lib.rs:2 #![feature(fs_walk)]
             ^~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib.rs:3:1: 3:18 error: unstable feature
src/lib.rs:3 #![feature(core)]
             ^~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
src/lib.rs:4:1: 4:32 error: unstable feature
src/lib.rs:4 #![feature(path_relative_from)]
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
note: this feature may not be used in the beta release channel
error: aborting due to 4 previous errors
Could not compile `cobalt`.

To learn more, run the command again with --verbose.
```

Rust Nightly
```
cobalt.rs ➤ rustc --version                                                                                                                                                                             git:master
rustc 1.2.0-nightly (f76d9bcfc 2015-05-28) (built 2015-05-28)
cobalt.rs ➤ cargo build                                                                                                                                                                                 git:master
   Compiling regex-syntax v0.1.0
   Compiling regex v0.1.32
   Compiling liquid v0.1.1 (https://github.com/cobalt-org/liquid-rust#96df4716)
   Compiling cobalt v0.0.1 (file:///home/benny/Development/rust/cobalt-org/cobalt.rs)
src/cobalt.rs:94:5: 94:36 warning: unused result which must be used, #[warn(unused_must_use)] on by default
src/cobalt.rs:94     file.read_to_string(&mut text);
                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/document.rs:78:13: 78:21 warning: variable does not need to be mutable, #[warn(unused_mut)] on by default
src/document.rs:78         let mut html = match self.as_html(post_data) {
                               ^~~~~~~~
```

**Comment by Liamsi** [comment]
That is strange indeed. I will check that tomorrow. Thank you for yout time!

**Comment by tak1n** [comment]
You're welcome.
Are you registered on gitter.im / skype etc so we can chat without spamming issue comments :)

**Comment by Liamsi** [comment]
Found it:
https://users.rust-lang.org/t/stable-versions-of-source-and-linux-binary-differ/1561

**Comment by tak1n** [comment]
:+1:

**Pull request closed without merging**
