### PR TITLE
Continuation of #227

### PR DESCRIPTION
**Pull request by epage**
- Improved the behavior of the immediate calls compared to the walking behavior
- Added tests for whitelisting

### CODE REVIEW

**Comment by epage** [comment]
Huh, I forgot I submitted #227.

@Svenito this includes tests for how to whitelist.  It seems odd that directories need extra work.  

So I guess the question is
- Is this just how gitignore works?
- Am I misusing burntsushi's crate?
- Is there a bug in burntsushi's crate?

**Comment by epage** [comment]
Also, I'll be on vacation tomorrow.  I'll have limited email but not access to my development machine.

**Comment by Svenito** [comment]
Thanks. I have it working now. The issue was that you have to quite the patterns because the `!` returns a blank line in the yaml parser.

**Comment by epage** [comment]
Good to know. We'll want to document that somewhere as a common pitfall.

**Comment by epage** [comment]
Printing the calls to `includes_path_leaf`

Windows:
```
Testing "/" true
Testing "/usr" false
Testing "/usr/cobalt" false
Testing "/usr/cobalt/site" false
Testing "/usr/cobalt/site/child" false
Testing "/usr/cobalt/site/child/child.txt" false
Testing "" false
Testing "." true
Testing "./child" false
Testing "./child/child.txt" false
test files::tests::files_includes_child_dir_file ... ok
```

Linux
```
---- files::tests::files_includes_child_dir_file stdout ----
        Testing "/" true
Testing "/usr" true
Testing "/usr/cobalt" false
Testing "/usr/cobalt/site" false
Testing "/usr/cobalt/site/child" false
Testing "/usr/cobalt/site/child/child.txt" false
Testing "" false
Testing "." true
thread 'files::tests::files_includes_child_dir_file' panicked at 'assertion failed: `(left == right)` (left: `false`, right: `true`)', src/files.rs:235
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by epage** [comment]
I've made a change to prevent us from recursing up past `root_dir`.  So it seems that my code is acting the same between Windows/Linux and that Gitignore is acting different.  Preparing a workaround.

**Pull request merged**
