### PR TITLE
Draft support

### PR DESCRIPTION
**Pull request by johannhof**
Clone from #124 because I made a new branch.

@LucioFranco ready to merge?

### CODE REVIEW

**Comment by LucioFranco** [comment]
@johannhof I have found an issue.

```
[info]   Using config file .cobalt.yml
[info]   Building from src into build
[trace]  Build configuration: Config { source: "src", dest: "build", layouts: "_layouts", drafts: "_drafts", include_drafts: true, posts: "posts", post_path: None, template_extensions: ["md", "liquid"], rss: Some("rss.xml"), name: Some("Amethyst"), description: Some("Everything should be made as simple as possible, but no simpler."), link: Some("https://amethyst.rs/"), ignore: [] }
[debug]  Layouts directory: "src/_layouts"
[debug]  posts directory: "src/posts"
[error]  yaml parsing error: unexpected character: `%' at line 4 column 7
[error]  Build not successful
```

This is what I get when I run `-L trace --drafts`. The [site](https://github.com/amethyst/website) builds when there are no arguments passed to the `build` command.

**Comment by johannhof** [comment]
@LucioFranco are you sure your drafts are not containing a yaml error somewhere?

**Comment by LucioFranco** [comment]
@johannhof that was the issue thanks. I found another issue. It does not seem to work with the layout. Only the 3 draft ones i have don't have style the rest do.

**Comment by johannhof** [comment]
Mmh assigning layouts works fine for me.

**Comment by LucioFranco** [comment]
You are right. It seems there was is an issue with the template we were using. Everything looks good. Will merge when tests pass! Great work this is going to be an awesome feature!

**Comment by johannhof** [comment]
Thanks for testing this so thoroughly! 👍

**Pull request merged**
