### PR TITLE
includes posts recursively into `post_data'

### PR DESCRIPTION
**Pull request by jianingy**
Hi, all

Currently, posts in subdirectories of `./posts' are missing in the post list in index.html. This patch helps fix this problem.

I've just tried cobalt a few days. Hope it's a valid fixing.

Thanks guys

### CODE REVIEW

**Comment by LucioFranco** [comment]
Thanks for the PR. Your tests seem to fail because of this [issue](https://github.com/contain-rs/vec-map/pull/22) and a bug in rustc on beta and nightly. Everything looks good to me. One thing is could you add some tests of subdirectories inside of the post path?

**Comment by jianingy** [comment]
Test is ok now. BTW, in order to check the content of 'index.html' in the middle of `run_test`. I have to split it into three sub-routines: configure, setup & cleanup.

**Comment by nott** [comment]
i wonder if the existing sorting makes sense when subdirectories are used
```
    // sort documents by date, if there's no date (none was provided or it couldn't be read) then
    // fall back to the default date
    posts.sort_by(|a, b| b.date.unwrap_or(default_date).cmp(&a.date.unwrap_or(default_date)));
```

and this pr needs to be rebased before merging

**Comment by uwearzt** [comment]
Hi, I made a similar fix :). Is this pull request abandoned? Then I would take it over and rebase it to master. 

BTW: I have used a little bit more clear variable names (IMHO) for the new Method:

```rust
fn starts_with_path(complete_path: &Path, post_path: &Path) -> bool {
    match (fs::canonicalize(complete_path), fs::canonicalize(post_path)) {
        (Ok(p), Ok(p2)) => p.starts_with(p2),
        _ => false,
    }
}
```

Are there any coding guidelines?

**Comment by johannhof** [comment]
I would assume you can go ahead and take it. :)

> Are there any coding guidelines?

Anything that passes [rustfmt](https://github.com/rust-lang-nursery/rustfmt) and [clippy](https://github.com/Manishearth/rust-clippy) (will be checked by CI).

Thank you!

**Comment by nott** [comment]
@uwearzt 

I don't have time to get this PR into master these weeks
so go ahead :) I can also help you to review your PR

**Comment by uwearzt** [comment]
can be closed, done with pull request #185

**Pull request closed without merging**
