### PR TITLE
refactor(collection): Rename Collection::pages to Collection::documents

### PR DESCRIPTION
**Pull request by Geobert**
and renamed parse_pages to parse_documents
for the [refactoring proposal](https://github.com/cobalt-org/cobalt.rs/issues/436)

### CODE REVIEW

**Comment by Geobert** [comment]
Why I keep forgetting running these tests… I've run fmt test and clippy but not the more important one… sorry, working on it

**Comment by Geobert** [comment]
It seems that `rustfmt` behaves differently between 1.24 and 1.25. I took the liberty to bump to the latest stable version

**Comment by epage** [comment]
I would have recommended on waiting until the proposal is accepted in case it isn't.

**Comment by Geobert** [comment]
It was not hard work so no bother if it's rejected. It made me understand better how cobalt works :)

**Comment by epage** [comment]
> It was not hard work so no bother if it's rejected. It made me understand better how cobalt works :)

Glad you are looking at it like that :)

One of my big concerns is ensuring contributors don't burn out.  That is one of the reasons I encourage communication so much.

**Comment by Geobert** [comment]
let's cancel this

**Pull request closed without merging**
