### PR TITLE
Added is_post gobal to allow users to detect if they are a post or not

### PR DESCRIPTION
**Pull request by LucioFranco**
Example usage:
```
{% if is_post %}
          {% include src/_layouts/post.liquid %}
{% else %}
          {{ content }}
{% endif %}
```

### CODE REVIEW

**Comment by johannhof** [comment]
Great idea! Two minor things:

- can you move this into the `get_attributes` function (line 58) so that we assign all attributes in a central place?
- please set the value to `false` if it's not a post :)

**Comment by LucioFranco** [comment]
@johannhof should be fixed. Sorry about that must have been very tired last night.

**Comment by tak1n** [comment]
@LucioFranco I think you forgot to add a else branch here: https://github.com/cobalt-org/cobalt.rs/blob/08245bf9e12c3f398f19bbeb5bfe87883a263f99/src/cobalt.rs#L72

If its not a post we need to set is_post to false.

**Comment by LucioFranco** [comment]
@tak1n it is already set to `false` by default. https://github.com/cobalt-org/cobalt.rs/blob/08245bf9e12c3f398f19bbeb5bfe87883a263f99/src/cobalt.rs#L282

**Comment by tak1n** [comment]
@LucioFranco another good point :smile: 
totally missed that

**Pull request merged**
