### PR TITLE
Add warning message if the current directory is being deleted.

### LINKED ISSUE #161: Add a warning if "cobalt clean" would delete the current working directory
Because that just happened to me.

### PR DESCRIPTION
**Pull request by kracekumar**
Fixes #161.

### CODE REVIEW

**Comment by kracekumar** [comment]
I am happy to modify if there is a different expectation for the warning message.

**Comment by LucioFranco** [comment]
@kracekumar thanks for contributing! The tests on master on travis seem to fail because of a nightly bug so don't worry about that. It looks good. I do not have time now to test but I would write a cli test and assert that this warning is displayed.

**Comment by kracekumar** [comment]
@LucioFranco I have added the test case for asserting the warning. Can you give your feedback? Apologies for last few commits where I had hiccup figuring out running integration tests. Do you want me to squash commits?

**Comment by johannhof** [comment]
This looks good but I realize I didn't quite word #161 correctly. Instead of warning, I would like to cancel the operation if the current directory would be deleted. I can not come up with scenario where a user would like to do that.

So it'd be great if you could change the `warn` into `error` and add a `std::process::exit(1);` :)

**Comment by kracekumar** [comment]
@johannhof I have fixed the PR as per latest comment.

**Comment by johannhof** [comment]
Ok, thanks! For some reason this is failing on Windows https://ci.appveyor.com/project/tak1n/cobalt-rs/build/1.0.117/job/8xrdoa78i0hbl5a2#L266

I would suggest to not create a new directory in fixtures, but use e.g. `tests/fixtures/example` instead. Maybe that fixes the Windows error, too.

**Comment by johannhof** [comment]
Hum, very strange. I'm pretty clueless why these failures on Windows are happening, I think I'd try to change the folders the tests are using to random other ones from the `fixtures` folder and see how that turns out.

**Comment by johannhof** [comment]
Alright, this has really been stale for long enough now. Sorry for that. I don't really know what the issue on Windows is, so I disabled the test on Windows for now. I'll make a new issue and whoever feels like it can investigate.

Thanks for the contribution!

**Pull request merged**
