### PR TITLE
fix(fmt) apply 1.28 rustfmt

### PR DESCRIPTION
**Pull request by Geobert**

### CODE REVIEW

**Comment by epage** [comment]
Please also update travis
https://github.com/cobalt-org/cobalt.rs/blob/master/.travis.yml#L29

**Comment by Geobert** [comment]
True, what about nightly version for clippy?

**Comment by epage** [comment]
> True, what about nightly version for clippy?

If you want.  I'd recommend doing it in a separate commit.

> EDIT: anyway to just say "latest stable" in travis like in appveyor?

We intentionally do not say "latest stable".  The concern is that an updated stable will break our build.

**Comment by epage** [comment]
Looks good!

Feel free to squash and let me know when done, and I'll merge.

**Comment by Geobert** [comment]
Squashed! :D

**Comment by epage** [comment]
Thanks!

**Pull request merged**
