### PR TITLE
Normalize EOL before diff

### PR DESCRIPTION
**Pull request by Geobert**
This fixes most of the tests, see https://github.com/cobalt-org/cobalt.rs/issues/241 for the remaining failing tests

### CODE REVIEW

**Comment by epage** [comment]
So you found that nearly all the tests fail with autocrlf enabled.

The only reason I can think of this happening is we are somehow inserting our own newlines into the content.  I think this is a problem in of itself and we should investigate and fix that.

In that case, this change could be masking a problem.  Once that is addressed, should this go in?  I'm mixed.
- This could mask future problems with newlines.  
- How much do we care about people without autocrlf messing up the content of the tests?

I think my preference is still towarsds editorconfig and maybe gitattribute.

**Comment by Geobert** [comment]
You're right, this normalization shouldn't be done on the test, but on the generated files

**Comment by epage** [comment]
I'm sorry that solving this hasn't been as straightforward as this originally seemed :(

**Comment by Geobert** [comment]
Don't worry, it's the correct decision ^^ That's why reviews are for ^^

**Pull request closed without merging**
